<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xsObject>
    <appSmsCode></appSmsCode>
    <sharePointRoot>
        <name>SharePoint Servers</name>
    </sharePointRoot>
    <wsdlroot>
        <wsdltree>
            <name>Web Services</name>
            <wsdlservice>
                <authenticationMode>basic</authenticationMode>
                <loaded>true</loaded>
                <name>localhost_services_organizer</name>
                <ntlmDomain></ntlmDomain>
                <ntlmHost></ntlmHost>
                <password></password>
                <preBuilt>false</preBuilt>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>validateLogin</id>
                    <ignoreProxy>false</ignoreProxy>
                    <intemplate>&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:end="http://endpoints.webservice.bs5lnd.org"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;end:validateLogin&gt;
         &lt;end:userid&gt;?&lt;/end:userid&gt;
         &lt;end:password&gt;?&lt;/end:password&gt;
      &lt;/end:validateLogin&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;</intemplate>
                    <inputStructure>
                        <index>-1</index>
                        <order>0</order>
                        <id>validateLogin</id>
                        <params>
                            <accessType></accessType>
                            <format>string</format>
                            <formatValue></formatValue>
                            <jsValue></jsValue>
                            <name>userid</name>
                            <type>java.lang.String</type>
                            <value></value>
                        </params>
                        <params>
                            <accessType></accessType>
                            <format>string</format>
                            <formatValue></formatValue>
                            <jsValue></jsValue>
                            <name>password</name>
                            <type>java.lang.String</type>
                            <value></value>
                        </params>
                    </inputStructure>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>validateLogin</operationname>
                    <outtemplate></outtemplate>
                    <outputStructure>
                        <index>-1</index>
                        <order>0</order>
                        <id>validateLoginResponse</id>
                        <params>
                            <accessType></accessType>
                            <format>boolean</format>
                            <formatValue></formatValue>
                            <jsValue></jsValue>
                            <name>validateLoginReturn</name>
                            <type>true or false</type>
                            <value></value>
                        </params>
                    </outputStructure>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://localhost:8080/organizer/services/LoginServiceEndpoint</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://localhost:8080/organizer/services/LoginServiceEndpoint?wsdl</wsdlurl>
                </soapservice>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>activateUser</id>
                    <ignoreProxy>false</ignoreProxy>
                    <intemplate>&lt;soapenv:Envelope xmlns:end="http://endpoints.webservice.bs5lnd.org" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;end:activateUser&gt;
         &lt;end:userid&gt;niranjan&lt;/end:userid&gt;
         &lt;end:secretcode&gt;92454&lt;/end:secretcode&gt;
      &lt;/end:activateUser&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;
</intemplate>
                    <inputStructure>
                        <index>-1</index>
                        <order>0</order>
                        <id>activateUser</id>
                        <params>
                            <accessType></accessType>
                            <format>string</format>
                            <formatValue></formatValue>
                            <jsValue></jsValue>
                            <name>userid</name>
                            <type>java.lang.String</type>
                            <value></value>
                        </params>
                        <params>
                            <accessType></accessType>
                            <format>string</format>
                            <formatValue></formatValue>
                            <jsValue></jsValue>
                            <name>secretcode</name>
                            <type>java.lang.String</type>
                            <value></value>
                        </params>
                    </inputStructure>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>activateUser</operationname>
                    <outtemplate>&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;
   &lt;soapenv:Body&gt;
      &lt;activateUserResponse xmlns="http://endpoints.webservice.bs5lnd.org"&gt;
         &lt;activateUserReturn&gt;true&lt;/activateUserReturn&gt;
      &lt;/activateUserResponse&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;
</outtemplate>
                    <outputStructure>
                        <index>-1</index>
                        <order>0</order>
                        <id>activateUserResponse</id>
                        <params>
                            <accessType></accessType>
                            <format>boolean</format>
                            <formatValue></formatValue>
                            <jsValue></jsValue>
                            <name>activateUserReturn</name>
                            <type>true or false</type>
                            <value></value>
                        </params>
                    </outputStructure>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://localhost:8080/organizer/services/LoginServiceEndpoint</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://localhost:8080/organizer/services/LoginServiceEndpoint?wsdl</wsdlurl>
                </soapservice>
                <sharePoint>false</sharePoint>
                <userName></userName>
                <wsdlurl>http://localhost:8080/organizer/services/LoginServiceEndpoint?wsdl</wsdlurl>
            </wsdlservice>
        </wsdltree>
    </wsdlroot>
</xsObject>
