//GlobalSequences File

function frProfile_frProfile_init_seq0(eventobject, neworientation){

popBlockingScreen.show(); 
frProfile.lblUserId.text = globalUserid;
setSessionForm.call(this,"frProfile");
 var updateProfile_inputparam = {};
 updateProfile_inputparam["serviceID"] = "updateProfile";
 
 
updateProfile_inputparam["httpheaders"] = {};

updateProfile_inputparam["httpconfig"] = {};

 



 updateProfile = appmiddlewareinvoker (updateProfile_inputparam, false);
 
//#ifdef iphone
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef bb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef bb10
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef winmobile
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef winmobile6x
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef winphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef android
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef xadvip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef xadvand
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef xadvbb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef xadvnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef bjs
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef basic
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef xadvpalm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef j2me
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef symbian
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef palm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef spaip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef spaan
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef spabb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef spawindows
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef spabbnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif

//#ifdef spawinphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30
//#endif
//#ifdef iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act30

frProfile.lblDOB.text = updateProfile.dob;
//#endif
 
//#ifdef iphone
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef bb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef bb10
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef winmobile
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef winmobile6x
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef winphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef android
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef xadvip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef xadvand
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef xadvbb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef xadvnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef bjs
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef basic
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef xadvpalm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef j2me
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef symbian
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef palm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef spaip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef spaan
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef spabb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef spawindows
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef spabbnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif

//#ifdef spawinphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31
//#endif
//#ifdef iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act31

frProfile.lblDOJ.text = updateProfile.doj;
//#endif
 
//#ifdef iphone
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef bb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef bb10
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef winmobile
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef winmobile6x
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef winphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef android
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef xadvip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef xadvand
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef xadvbb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef xadvnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef bjs
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef basic
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef xadvpalm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef j2me
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef symbian
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef palm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef spaip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef spaan
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef spabb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef spawindows
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef spabbnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif

//#ifdef spawinphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32
//#endif
//#ifdef iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act32

frProfile.txtEmailId.text = updateProfile.emailId;
//#endif
 
//#ifdef iphone
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef bb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef bb10
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef winmobile
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef winmobile6x
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef winphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef android
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef xadvip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef xadvand
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef xadvbb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef xadvnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef bjs
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef basic
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef xadvpalm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef j2me
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef symbian
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef palm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef spaip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef spaan
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef spabb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef spawindows
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef spabbnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif

//#ifdef spawinphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33
//#endif
//#ifdef iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act33

frProfile.txtFullName.text = updateProfile.fullName;
//#endif
 
//#ifdef iphone
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef bb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef bb10
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef winmobile
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef winmobile6x
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef winphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef android
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef xadvip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef xadvand
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef xadvbb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef xadvnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef bjs
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef basic
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef xadvpalm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef j2me
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef symbian
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef palm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef spaip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef spaan
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef spabb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef spawindows
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef spabbnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif

//#ifdef spawinphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34
//#endif
//#ifdef iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act34

frProfile.txtAddress.text = updateProfile.address;
//#endif
 
//#ifdef iphone
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef bb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef bb10
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef winmobile
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef winmobile6x
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef winphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef android
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef xadvip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef xadvand
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef xadvbb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef xadvnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef bjs
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef basic
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef xadvpalm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef j2me
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef symbian
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef palm
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef spaip
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef spaan
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef spabb
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef spawindows
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef spabbnth
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif

//#ifdef spawinphone8
 //#define iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35
//#endif
//#ifdef iphone_bb_bb10_winmobile_winmobile6x_winphone8_android_xadvip_xadvand_xadvbb_xadvnth_bjs_basic_xadvpalm_j2me_symbian_palm_spaip_spaan_spabb_spawindows_spabbnth_spawinphone8_deffrProfile_frProfile_init_seq0_act35

frProfile.txtAlias.text = updateProfile.alias;
//#endif
 

popBlockingScreen.dismiss();

};

